import Content from './content';

export var CONTENTBLOGS: Content[] = [
  {"id": 1, "title": "Title1", "slug": "BlogsPost1", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 2, "title": "Title2", "slug": "BlogsPost2", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 3, "title": "Title3", "slug": "BlogsPost3", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 4, "title": "Title4", "slug": "BlogsPost4", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 5, "title": "Title5", "slug": "BlogsPost5", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 6, "title": "Title6", "slug": "BlogsPost6", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 7, "title": "Title7", "slug": "BlogsPost7", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 8, "title": "Title8", "slug": "BlogsPost8", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 9, "title": "Title9", "slug": "BlogsPost9", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 10, "title": "Title10", "slug": "BlogsPost10", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 11, "title": "Title11", "slug": "BlogsPost11", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 12, "title": "Title12", "slug": "BlogsPost12", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 13, "title": "Title13", "slug": "BlogsPost13", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 14, "title": "Title14", "slug": "BlogsPost14", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 15, "title": "Title15", "slug": "BlogsPost15", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 16, "title": "Title16", "slug": "BlogsPost16", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 17, "title": "Title17", "slug": "BlogsPost17", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 18, "title": "Title18", "slug": "BlogsPost18", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 19, "title": "Title19", "slug": "BlogsPost19", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 20, "title": "Title20", "slug": "BlogsPost20", "dateCreated": "2", "dateModified": "3", "datePublished": "4"}
];

export var CONTENTQUOTES: Content[] = [
  {"id": 1, "title": "Title1", "slug": "Quote1", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 2, "title": "Title2", "slug": "Quote2", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 3, "title": "Title3", "slug": "Quote3", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 4, "title": "Title4", "slug": "Quote4", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 5, "title": "Title5", "slug": "Quote5", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 6, "title": "Title6", "slug": "Quote6", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 7, "title": "Title7", "slug": "Quote7", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 8, "title": "Title8", "slug": "Quote8", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 9, "title": "Title9", "slug": "Quote9", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 10, "title": "Title10", "slug": "Quote10", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 11, "title": "Title11", "slug": "Quote11", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 12, "title": "Title12", "slug": "Quote12", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 13, "title": "Title13", "slug": "Quote13", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 14, "title": "Title14", "slug": "Quote14", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 15, "title": "Title15", "slug": "Quote15", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 16, "title": "Title16", "slug": "Quote16", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 17, "title": "Title17", "slug": "Quote17", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 18, "title": "Title18", "slug": "Quote18", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 19, "title": "Title19", "slug": "Quote19", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 20, "title": "Title20", "slug": "Quote20", "dateCreated": "2", "dateModified": "3", "datePublished": "4"}
];

export var CONTENTMUSICALINSTRUMENTS: Content[] = [
  {"id": 1, "title": "Title1", "slug": "MusicalInstrument1", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 2, "title": "Title2", "slug": "MusicalInstrument2", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 3, "title": "Title3", "slug": "MusicalInstrument3", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 4, "title": "Title4", "slug": "MusicalInstrument4", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 5, "title": "Title5", "slug": "MusicalInstrument5", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 6, "title": "Title6", "slug": "MusicalInstrument6", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 7, "title": "Title7", "slug": "MusicalInstrument7", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 8, "title": "Title8", "slug": "MusicalInstrument8", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 9, "title": "Title9", "slug": "MusicalInstrument9", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 10, "title": "Title10", "slug": "MusicalInstrument10", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 11, "title": "Title11", "slug": "MusicalInstrument11", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 12, "title": "Title12", "slug": "MusicalInstrument12", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 13, "title": "Title13", "slug": "MusicalInstrument13", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 14, "title": "Title14", "slug": "MusicalInstrument14", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 15, "title": "Title15", "slug": "MusicalInstrument15", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 16, "title": "Title16", "slug": "MusicalInstrument16", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 17, "title": "Title17", "slug": "MusicalInstrument17", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 18, "title": "Title18", "slug": "MusicalInstrument18", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 19, "title": "Title19", "slug": "MusicalInstrument19", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 20, "title": "Title20", "slug": "MusicalInstrument20", "dateCreated": "2", "dateModified": "3", "datePublished": "4"}
];

export var CONTENTBOOKS: Content[] = [
  {"id": 1, "title": "Title1", "slug": "Book1", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 2, "title": "Title2", "slug": "Book2", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 3, "title": "Title3", "slug": "Book3", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 4, "title": "Title4", "slug": "Book4", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 5, "title": "Title5", "slug": "Book5", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 6, "title": "Title6", "slug": "Book6", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 7, "title": "Title7", "slug": "Book7", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 8, "title": "Title8", "slug": "Book8", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 9, "title": "Title9", "slug": "Book9", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 10, "title": "Title10", "slug": "Book10", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 11, "title": "Title11", "slug": "Book11", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 12, "title": "Title12", "slug": "Book12", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 13, "title": "Title13", "slug": "Book13", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 14, "title": "Title14", "slug": "Book14", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 15, "title": "Title15", "slug": "Book15", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 16, "title": "Title16", "slug": "Book16", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 17, "title": "Title17", "slug": "Book17", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 18, "title": "Title18", "slug": "Book18", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 19, "title": "Title19", "slug": "Book19", "dateCreated": "2", "dateModified": "3", "datePublished": "4"},
  {"id": 20, "title": "Title20", "slug": "Book20", "dateCreated": "2", "dateModified": "3", "datePublished": "4"}
];